version: "3.9"

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "80:8000"
    env_file:
      - .env
    volumes:
      - .:/app
    restart: always
